/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/catalog/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Shop items */
        get: {
            parameters: {
                query?: {
                    category?: string;
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Items */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CatalogItem"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/items/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Shop item by slug */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Item */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CatalogItem"];
                    };
                };
                404: components["responses"]["Problem"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/materials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Digital materials with rendering presets and rates */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Materials */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Material"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Template descriptors (cached from the geometry service) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Descriptors */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["template-descriptor.v1"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Descriptor */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["template-descriptor.v1"];
                    };
                };
                404: components["responses"]["Problem"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/designs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a design
         * @description Shop path: `catalog_item_slug` (template and defaults come from the item).
         *     Remix-lite / direct path: `template_id` + optional `params`.
         *     Create path: `prompt` → 422 until Phase 2.
         *     Returns 202 with the design and the first generation job. Follow `/api/jobs/{id}/events`.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateDesignRequest"];
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DesignAccepted"];
                    };
                };
                400: components["responses"]["Problem"];
                404: components["responses"]["Problem"];
                422: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/designs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Design with latest version */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Design"];
                    };
                };
                404: components["responses"]["Problem"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/designs/{id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Versions, newest first */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DesignVersion"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/versions/{versionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    versionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Version */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DesignVersion"];
                    };
                };
                404: components["responses"]["Problem"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/versions/{versionId}/params": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Edit parameters → new version (new job) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    versionId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        params: {
                            [key: string]: number | boolean | string;
                        };
                        material?: string;
                    };
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DesignAccepted"];
                    };
                };
                404: components["responses"]["Problem"];
                422: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/versions/{versionId}/printability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    versionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Report */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["printability-report.v1"];
                    };
                };
                404: components["responses"]["Problem"];
                /** @description Version not ready yet */
                409: components["responses"]["Problem"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/versions/{versionId}/price": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Price breakdown for a material */
        get: {
            parameters: {
                query: {
                    material: string;
                };
                header?: never;
                path: {
                    versionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Breakdown */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["price-breakdown.v1"];
                    };
                };
                404: components["responses"]["Problem"];
                /** @description Version not ready yet */
                409: components["responses"]["Problem"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Job */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Job"];
                    };
                };
                404: components["responses"]["Problem"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{jobId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server-Sent Events stream of job stages
         * @description `text/event-stream`. Each event is `event: stage` with a JSON `data` body shaped like
         *     `JobStageEvent`. The stream replays the current stage on connect and closes after
         *     `ready` or `failed`. Clients reconnect with `Last-Event-ID` (the sequence number).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Event stream */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/otp/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request a sign-in code for a phone number */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description E.164 Indian mobile */
                        phone: string;
                    };
                };
            };
            responses: {
                /** @description Code sent (or mocked) */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            request_id: string;
                            expires_in_s: number;
                            /** @description Only in the local profile with the mock OTP sender */
                            dev_code?: string;
                        };
                    };
                };
                400: components["responses"]["Problem"];
                /** @description Too many requests for this phone (otp_rate_limited) */
                429: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/otp/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify the code, sign in, attach guest designs and cart */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Guest identity generated by the browser; ignored when a bearer token is present. */
                    "X-Aakar-Guest"?: components["parameters"]["GuestHeader"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        request_id: string;
                        code: string;
                    };
                };
            };
            responses: {
                /** @description Signed in */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Session"];
                    };
                };
                400: components["responses"]["Problem"];
                /** @description Wrong or expired code (otp_invalid / otp_expired) */
                401: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                401: components["responses"]["Problem"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update profile */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name?: string;
                        /** Format: email */
                        email?: string;
                    };
                };
            };
            responses: {
                /** @description User */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                401: components["responses"]["Problem"];
            };
        };
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the current session token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Revoked */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/addresses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Addresses */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Address"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AddressInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Address"];
                    };
                };
                422: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/addresses/{addressId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    addressId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AddressInput"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Address"];
                    };
                };
                404: components["responses"]["Problem"];
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    addressId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["Problem"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The current identity's cart (user or guest) */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Guest identity generated by the browser; ignored when a bearer token is present. */
                    "X-Aakar-Guest"?: components["parameters"]["GuestHeader"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cart */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Cart"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Empty the cart */
        delete: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Guest identity generated by the browser; ignored when a bearer token is present. */
                    "X-Aakar-Guest"?: components["parameters"]["GuestHeader"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cart */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Cart"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cart/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add a design version in a finish
         * @description The version must be ready and pass printability. The unit price is snapshotted from the active pricing policy at add time and refreshed on GET /api/cart when the policy changes (the item then carries repriced = true).
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Guest identity generated by the browser; ignored when a bearer token is present. */
                    "X-Aakar-Guest"?: components["parameters"]["GuestHeader"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        version_id: string;
                        material: string;
                        /** @default 1 */
                        qty?: number;
                    };
                };
            };
            responses: {
                /** @description Cart */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Cart"];
                    };
                };
                404: components["responses"]["Problem"];
                /** @description Version not ready (version_not_ready) or failed printability (not_printable) */
                409: components["responses"]["Problem"];
                422: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cart/items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Guest identity generated by the browser; ignored when a bearer token is present. */
                    "X-Aakar-Guest"?: components["parameters"]["GuestHeader"];
                };
                path: {
                    itemId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cart */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Cart"];
                    };
                };
                404: components["responses"]["Problem"];
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Guest identity generated by the browser; ignored when a bearer token is present. */
                    "X-Aakar-Guest"?: components["parameters"]["GuestHeader"];
                };
                path: {
                    itemId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        qty?: number;
                        material?: string;
                    };
                };
            };
            responses: {
                /** @description Cart */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Cart"];
                    };
                };
                404: components["responses"]["Problem"];
            };
        };
        trace?: never;
    };
    "/api/shipping/serviceability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Can we deliver to this pincode, and how fast */
        get: {
            parameters: {
                query: {
                    pincode: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Serviceability */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            pincode: string;
                            serviceable: boolean;
                            /** @description delhivery, or mock-delhivery */
                            carrier: string;
                            eta_days?: number;
                            cod_available?: boolean;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Turn the cart into an order awaiting payment
         * @description Snapshots items, prices and address into the order; creates a payment with the configured gateway (mock by default) and returns where to pay. The cart is emptied when payment succeeds.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        address_id: string;
                        /** @default true */
                        notify_whatsapp?: boolean;
                        note?: string;
                    };
                };
            };
            responses: {
                /** @description Order created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CheckoutResult"];
                    };
                };
                401: components["responses"]["Problem"];
                /** @description Cart empty (cart_empty) or an item no longer purchasable (not_printable) */
                409: components["responses"]["Problem"];
                /** @description Address not serviceable (not_serviceable) */
                422: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Orders newest first */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrderSummary"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Order */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Order"];
                    };
                };
                404: components["responses"]["Problem"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{orderId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server-Sent Events of order stage changes
         * @description event = stage, data = OrderEvent; replays after Last-Event-ID; closes after delivered or cancelled.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Event stream */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{orderId}/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a new payment attempt for an order still awaiting payment
         * @description Used after a failed or abandoned payment. Only while the order is pending_payment; the previous attempt is left as failed.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description New payment */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Payment"];
                    };
                };
                404: components["responses"]["Problem"];
                /** @description Order is not awaiting payment (order_not_payable) */
                409: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/{paymentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    paymentId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Payment */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Payment"];
                    };
                };
                404: components["responses"]["Problem"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/{paymentId}/mock/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Placeholder gateway page reports the outcome (mock gateway only)
         * @description Enabled only when the payment's gateway is mock. Real gateways confirm through their webhook endpoints instead. Runs the same confirmation path a webhook would.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    paymentId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        outcome: "success" | "failure";
                        /**
                         * @default upi
                         * @enum {string}
                         */
                        method?: "upi" | "card" | "netbanking";
                    };
                };
            };
            responses: {
                /** @description Payment after confirmation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Payment"];
                    };
                };
                404: components["responses"]["Problem"];
                /** @description Not a mock payment or already final (payment_final) */
                409: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/jobs/{jobId}/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Direct-profile callback from the geometry service
         * @description Not exposed publicly. Accepts a `design.progress`, `design.completed` or `design.failed` envelope.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["envelope.v1"];
                };
            };
            responses: {
                /** @description Recorded */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            /** Format: uuid */
            id: string;
            phone: string;
            name?: string | null;
            email?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        Session: {
            access_token: string;
            /** @constant */
            token_type: "Bearer";
            expires_in_s: number;
            user: components["schemas"]["User"];
            /** @description What was moved from the guest identity to the user on this sign-in. */
            attached: {
                designs?: number;
                cart_items?: number;
            };
        };
        AddressInput: {
            /** @description Home or Office */
            label?: string;
            name: string;
            phone: string;
            line1: string;
            line2?: string;
            city: string;
            state: string;
            pincode: string;
            /** @default false */
            is_default: boolean;
        };
        Address: components["schemas"]["AddressInput"] & {
            /** Format: uuid */
            id: string;
        };
        CartItem: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            design_id: string;
            /** Format: uuid */
            version_id: string;
            version_no?: number;
            title: string;
            /** @description e.g. Terracotta Silk · 92 × 78 × 120 mm · 55 g */
            specs_line?: string;
            material_id: string;
            material_name?: string;
            qty: number;
            unit_price: components["schemas"]["price-breakdown.v1"];
            line_total_paise: number;
            thumbnail_url?: string | null;
            /** @description False when the version failed printability or the template is no longer live */
            purchasable: boolean;
            /** @description True when the active pricing policy changed since the item was added */
            repriced?: boolean;
        };
        Cart: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            owner: "user" | "guest";
            items: components["schemas"]["CartItem"][];
            subtotal_paise: number;
            shipping_paise: number;
            shipping_label?: string;
            total_paise: number;
            policy_version: string;
            /** Format: date-time */
            updated_at: string;
        };
        /**
         * @description Internal status. The customer stage is derived.
         * @enum {string}
         */
        OrderStatus: "pending_payment" | "confirmed" | "queued" | "slicing" | "printing" | "finishing" | "qc" | "packed" | "shipped" | "delivered" | "cancelled" | "on_hold" | "reprint";
        /**
         * @description Customer-facing collapsed stage (board 06).
         * @enum {string}
         */
        OrderStage: "payment" | "queued" | "slicing" | "printing" | "sanding" | "shipped" | "delivered" | "cancelled";
        OrderItem: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            design_id: string;
            /** Format: uuid */
            version_id: string;
            version_no?: number;
            title: string;
            specs_line?: string;
            material_id: string;
            material_name?: string;
            qty: number;
            unit_price: components["schemas"]["price-breakdown.v1"];
            line_total_paise: number;
            /** @description Snapshot of the version assets at order time */
            assets?: {
                [key: string]: unknown;
            };
        };
        OrderSummary: {
            /** Format: uuid */
            id: string;
            /** @description AK-000001 */
            number: string;
            status: components["schemas"]["OrderStatus"];
            stage: components["schemas"]["OrderStage"];
            /** @description First item title plus a count of the others */
            title?: string;
            total_paise: number;
            items_count: number;
            /** Format: date */
            eta?: string | null;
            /** Format: date-time */
            placed_at: string;
        };
        Order: components["schemas"]["OrderSummary"] & {
            items: components["schemas"]["OrderItem"][];
            address: components["schemas"]["Address"];
            subtotal_paise: number;
            shipping_paise: number;
            shipping_label?: string;
            policy_version?: string;
            payment: components["schemas"]["Payment"];
            shipment?: components["schemas"]["Shipment"];
            events: components["schemas"]["OrderEvent"][];
            notify_whatsapp?: boolean;
            note?: string | null;
        };
        OrderEvent: {
            sequence: number;
            status: components["schemas"]["OrderStatus"];
            stage: components["schemas"]["OrderStage"];
            message: string;
            /** @description Studio, printer bay and layer height for the tracking board */
            detail?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            at: string;
        };
        Payment: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            order_id: string;
            /** @description mock or razorpay */
            gateway: string;
            /** @description Provider order or payment id */
            gateway_ref?: string | null;
            /** @enum {string} */
            status: "created" | "pending" | "succeeded" | "failed" | "refunded";
            method?: string | null;
            amount_paise: number;
            /** @constant */
            currency: "INR";
            /** @description Where the customer pays; the placeholder page for the mock gateway */
            pay_url?: string | null;
            invoice_number?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            finished_at?: string | null;
        };
        Shipment: {
            /** Format: uuid */
            id: string;
            carrier: string;
            awb?: string | null;
            /** @enum {string} */
            status: "created" | "picked_up" | "in_transit" | "out_for_delivery" | "delivered" | "returned";
            /** Format: date */
            eta?: string | null;
            tracking_url?: string | null;
            events?: {
                status?: string;
                message?: string;
                /** Format: date-time */
                at?: string;
            }[];
        };
        CheckoutResult: {
            /** Format: uuid */
            order_id: string;
            order_number: string;
            payment: components["schemas"]["Payment"];
        };
        CatalogItem: {
            slug: string;
            /** @description False until the item's template exists in the geometry service; the Shop shows a 'Coming soon' ribbon and POST /api/designs answers 422 template_not_available. */
            available: boolean;
            name: string;
            /** @enum {string} */
            category: "home_decor" | "nameplates" | "kitchen" | "desk_tech" | "gifting";
            description?: string;
            template_id: string;
            default_params: {
                [key: string]: unknown;
            };
            default_material: string;
            base_price_paise: number;
            /** @description e.g. 'Fits phones to 6.9″ · 92 × 78 × 120 mm · 64 g' */
            specs_line: string;
            environment?: string;
            media?: {
                kind?: string;
                url?: string;
            }[];
        };
        Material: {
            id: string;
            name: string;
            filament: string;
            density_g_cm3: number;
            /** @enum {string} */
            finish_class: "matte" | "silk";
            rate_per_g_paise: number;
            heat_safe?: boolean;
            pbr: {
                /** @description sRGB hex */
                color: string;
                roughness: number;
                metalness: number;
                clearcoat?: number;
                clearcoat_roughness?: number;
                sheen?: number;
                sheen_color?: string;
            };
        };
        CreateDesignRequest: {
            /** @enum {string} */
            source: "shop" | "create" | "remix";
            catalog_item_slug?: string;
            template_id?: string;
            params?: {
                [key: string]: number | boolean | string;
            };
            material?: string;
            prompt?: string;
            title?: string;
        };
        DesignAccepted: {
            /** Format: uuid */
            design_id: string;
            version_no: number;
            /** Format: uuid */
            job_id: string;
            events_url: string;
        };
        Design: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            source: "shop" | "create" | "remix";
            catalog_item_slug?: string | null;
            title: string;
            /** @enum {string} */
            status: "generating" | "ready" | "failed";
            /** Format: date-time */
            created_at: string;
            versions_count: number;
            latest_version?: components["schemas"]["DesignVersion"];
        };
        DesignVersion: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            design_id: string;
            version_no: number;
            /** Format: uuid */
            parent_version_id?: string | null;
            /** @enum {string} */
            status: "generating" | "ready" | "failed";
            spec: components["schemas"]["design-spec.v1"];
            template?: {
                id?: string;
                version?: number;
            };
            assets?: {
                [key: string]: unknown;
            };
            /** @description bounds_mm */
            geometry?: {
                [key: string]: unknown;
            };
            printability?: components["schemas"]["printability-report.v1"];
            print_estimate?: components["schemas"]["print-estimate.v1"];
            /** @description For spec.material */
            price?: components["schemas"]["price-breakdown.v1"];
            karigar_note?: string;
            /** Format: uuid */
            job_id?: string;
            /** @enum {string} */
            created_by: "user" | "agent" | "system";
            /** Format: date-time */
            created_at: string;
        };
        Job: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            design_id: string;
            /** Format: uuid */
            version_id?: string | null;
            version_no: number;
            /** @enum {string} */
            type: "generate";
            /** @enum {string} */
            status: "queued" | "running" | "succeeded" | "failed";
            /** @enum {string} */
            stage: "queued" | "understanding" | "sculpting" | "checking" | "pricing" | "ready" | "failed";
            message?: string;
            error_code?: string | null;
            attempts?: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            finished_at?: string | null;
        };
        JobStageEvent: {
            /** Format: uuid */
            job_id: string;
            sequence: number;
            /** @enum {string} */
            stage: "queued" | "understanding" | "sculpting" | "checking" | "pricing" | "ready" | "failed";
            message: string;
            percent?: number;
            /** Format: uuid */
            version_id?: string | null;
            error_code?: string | null;
            /** Format: date-time */
            at: string;
        };
        param: {
            /** @enum {string} */
            type: "number" | "integer" | "boolean" | "enum";
            label: string;
            description?: string;
            /** @enum {string} */
            unit?: "mm" | "deg" | "count" | "";
            default: unknown;
            min?: number;
            max?: number;
            step?: number;
            options?: string[];
            /**
             * @description Exposed as a draggable morph handle in the viewer.
             * @default false
             */
            handle: boolean;
            /** @description UI grouping, e.g. Size, Shape, Details. */
            group?: string;
        };
        anchor: {
            id: string;
            label: string;
            /** @enum {string} */
            projection: "planar" | "cylindrical" | "conformal";
            max_text_height_mm?: number;
        };
        /**
         * Aakar Template Descriptor v1
         * @description What a parametric template publishes about itself: parameters with ranges, anchors for text and motifs, handles for morph nodes, constraints and allowed materials. Served by the geometry service and cached by the API.
         */
        "template-descriptor.v1": {
            id: string;
            version: number;
            family: string;
            name: string;
            description?: string;
            /**
             * @default studio
             * @enum {string}
             */
            environment: "studio" | "teak_table_candlelight" | "desk_oak" | "dashboard" | "kitchen_marble" | "balcony_daylight";
            params: {
                [key: string]: components["schemas"]["param"];
            };
            anchors: components["schemas"]["anchor"][];
            constraints: {
                min_wall_mm: number;
                max_overhang_deg: number;
                bed_mm: number[];
            };
            materials: string[];
            /** @default [] */
            style_variants: ("jaipur_heritage" | "modern_zen" | "cyber_desi" | "warli_line")[];
            /** @default [] */
            features_supported: ("emboss_text" | "motif")[];
            $defs: {
                param: {
                    /** @enum {string} */
                    type: "number" | "integer" | "boolean" | "enum";
                    label: string;
                    description?: string;
                    /** @enum {string} */
                    unit?: "mm" | "deg" | "count" | "";
                    default: unknown;
                    min?: number;
                    max?: number;
                    step?: number;
                    options?: string[];
                    /**
                     * @description Exposed as a draggable morph handle in the viewer.
                     * @default false
                     */
                    handle: boolean;
                    /** @description UI grouping, e.g. Size, Shape, Details. */
                    group?: string;
                };
                anchor: {
                    id: string;
                    label: string;
                    /** @enum {string} */
                    projection: "planar" | "cylindrical" | "conformal";
                    max_text_height_mm?: number;
                };
            };
        };
        emboss_text: {
            /** @constant */
            type: "emboss_text";
            text: string;
            /**
             * @description Detected or chosen script; picks the shaping font.
             * @enum {string}
             */
            script?: "latin" | "devanagari" | "telugu" | "tamil" | "kannada" | "bengali" | "gujarati";
            font?: string;
            /** @default 1.2 */
            depth_mm: number;
            height_mm?: number;
            /** @description Anchor id from the template descriptor. */
            anchor: string;
            /**
             * @default planar
             * @enum {string}
             */
            projection: "planar" | "cylindrical" | "conformal";
            /**
             * @default emboss
             * @enum {string}
             */
            mode: "emboss" | "deboss";
        };
        motif: {
            /** @constant */
            type: "motif";
            motif_id: string;
            anchor: string;
            /** @default 1 */
            scale: number;
            /** @default 1 */
            depth_mm: number;
            /**
             * @default deboss
             * @enum {string}
             */
            mode: "emboss" | "deboss";
        };
        feature: components["schemas"]["emboss_text"] | components["schemas"]["motif"];
        constraints: {
            /** @default 1.2 */
            min_wall_mm: number;
            /** @default 55 */
            max_overhang_deg: number;
            /**
             * @default [
             *       250,
             *       250,
             *       250
             *     ]
             */
            bed_mm: number[];
        };
        /**
         * Aakar Design Spec v1
         * @description The only thing the co-designer agent (or a viewer control) may hand to the geometry service. Geometry is produced by our own templates from this document; no executable code ever crosses this boundary.
         */
        "design-spec.v1": {
            /** @constant */
            spec_version: "1.0";
            /** @description Template family id, e.g. phone_stand, table_lamp. */
            family: string;
            /** @description Template id with version, e.g. jharokha_phone_stand@1. */
            template: string;
            /** @description Parameter values. Keys and ranges are defined by the template descriptor. */
            params: {
                [key: string]: number | boolean | string;
            };
            /** @default [] */
            features: components["schemas"]["feature"][];
            /**
             * @default none
             * @enum {string}
             */
            style: "none" | "jaipur_heritage" | "modern_zen" | "cyber_desi" | "warli_line";
            /** @description Digital material id, e.g. terracotta_silk. Affects rendering and price, never geometry. */
            material?: string;
            constraints?: components["schemas"]["constraints"];
            $defs: {
                constraints: {
                    /** @default 1.2 */
                    min_wall_mm: number;
                    /** @default 55 */
                    max_overhang_deg: number;
                    /**
                     * @default [
                     *       250,
                     *       250,
                     *       250
                     *     ]
                     */
                    bed_mm: number[];
                };
                feature: components["schemas"]["emboss_text"] | components["schemas"]["motif"];
                emboss_text: {
                    /** @constant */
                    type: "emboss_text";
                    text: string;
                    /**
                     * @description Detected or chosen script; picks the shaping font.
                     * @enum {string}
                     */
                    script?: "latin" | "devanagari" | "telugu" | "tamil" | "kannada" | "bengali" | "gujarati";
                    font?: string;
                    /** @default 1.2 */
                    depth_mm: number;
                    height_mm?: number;
                    /** @description Anchor id from the template descriptor. */
                    anchor: string;
                    /**
                     * @default planar
                     * @enum {string}
                     */
                    projection: "planar" | "cylindrical" | "conformal";
                    /**
                     * @default emboss
                     * @enum {string}
                     */
                    mode: "emboss" | "deboss";
                };
                motif: {
                    /** @constant */
                    type: "motif";
                    motif_id: string;
                    anchor: string;
                    /** @default 1 */
                    scale: number;
                    /** @default 1 */
                    depth_mm: number;
                    /**
                     * @default deboss
                     * @enum {string}
                     */
                    mode: "emboss" | "deboss";
                };
            };
        };
        check: {
            /** @enum {string} */
            status: "pass" | "warn" | "fail" | "skipped";
            /** @description Customer-facing sentence, e.g. 'Inside base · 3 mm'. */
            summary: string;
            value?: number | boolean | null;
            unit?: string;
            threshold?: number | null;
            detail?: {
                [key: string]: unknown;
            };
        };
        /**
         * Aakar Printability Report v1
         * @description Produced by the inspect service for every design version. The checkout stability card renders directly from this.
         */
        "printability-report.v1": {
            /** @constant */
            report_version: "1.0";
            /** @description True when every check with severity 'fail' passed. */
            passed: boolean;
            geometry: {
                /** @description Width, depth, height. */
                bounds_mm: number[];
                volume_cm3: number;
                surface_cm2: number;
                triangles: number;
            };
            checks: {
                manifold: components["schemas"]["check"];
                fits_bed: components["schemas"]["check"];
                thinnest_wall: components["schemas"]["check"];
                centre_of_gravity: components["schemas"]["check"];
                tipping_margin: components["schemas"]["check"];
                overhangs?: components["schemas"]["check"];
                load_capacity?: components["schemas"]["check"];
            };
            check_duration_ms: number;
            $defs: {
                check: {
                    /** @enum {string} */
                    status: "pass" | "warn" | "fail" | "skipped";
                    /** @description Customer-facing sentence, e.g. 'Inside base · 3 mm'. */
                    summary: string;
                    value?: number | boolean | null;
                    unit?: string;
                    threshold?: number | null;
                    detail?: {
                        [key: string]: unknown;
                    };
                };
            };
        };
        /**
         * Aakar Print Estimate v1
         * @description Material-independent slicing estimate. Mass per material is derived by the API from extruded_volume_cm3 x material density, so a finish swap re-prices without re-slicing.
         */
        "print-estimate.v1": {
            /** @enum {string} */
            method: "prusaslicer_cli" | "orcaslicer_cli" | "heuristic";
            slicer_version?: string;
            print_seconds: number;
            /** @description Filament volume actually deposited (walls, infill, top/bottom, supports). */
            extruded_volume_cm3: number;
            layer_height_mm: number;
            infill_pct: number;
            layers?: number;
            supports_required?: boolean;
        };
        /**
         * Aakar Price Breakdown v1
         * @description Computed by the API pricing module from a print estimate and a material. All amounts are integer paise (INR minor units). Snapshotted into cart and order so totals never drift.
         */
        "price-breakdown.v1": {
            /** @constant */
            currency: "INR";
            material_id: string;
            mass_g: number;
            print_seconds: number;
            lines: {
                /** @enum {string} */
                code: "material" | "machine_time" | "finishing" | "packaging";
                /** @description Customer-facing, e.g. 'Material · 84 g' or 'Print time · 3 h 40 m'. */
                label: string;
                detail?: string;
                amount_paise: number;
            }[];
            /** @description Sum of lines with margin applied and rounded to a price ending in 9 rupees. */
            subtotal_paise: number;
            /** @description 0 when free. */
            shipping_paise: number;
            shipping_label?: string;
            total_paise: number;
            policy_version: string;
        };
        /**
         * Aakar Event Envelope v1
         * @description Every message on RabbitMQ (exchange 'aakar.design', topic) uses this envelope. Routing key equals 'type'. Consumers must be idempotent on (job_id, type, sequence).
         */
        "envelope.v1": {
            /** @enum {string} */
            type: "design.generate" | "design.progress" | "design.completed" | "design.failed";
            /** @constant */
            version: 1;
            /** Format: uuid */
            event_id: string;
            /** Format: uuid */
            job_id: string;
            /** Format: uuid */
            design_id: string;
            /** Format: date-time */
            occurred_at: string;
            /** @description Per-job monotonic counter for progress ordering. */
            sequence?: number;
            payload: Record<string, never>;
        };
    };
    responses: {
        /** @description Problem Details */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    type?: string;
                    title?: string;
                    status?: number;
                    detail?: string;
                    instance?: string;
                    /** @description Stable machine code, e.g. not_found, not_yet_available, param_out_of_range, version_not_ready, unauthenticated, otp_invalid, otp_expired, otp_rate_limited, not_printable, cart_empty, not_serviceable, payment_final */
                    code?: string;
                };
            };
        };
    };
    parameters: {
        /** @description Guest identity generated by the browser; ignored when a bearer token is present. */
        GuestHeader: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
