"""Print estimate v1: material-independent extruded volume and print time (PLAN §7.10).

Two backends behind the :class:`SlicerBackend` protocol:

* :class:`HeuristicEstimator` (default) - closed-form model from mesh volume/area. No slicer needed.
* :class:`PrusaSlicerCli` - real slice via ``prusa-slicer --export-gcode`` when ``AAKAR_SLICER_BIN``
  points at an existing binary; parses the G-code footer.
"""

from __future__ import annotations

import logging
import math
import os
import re
import shutil
import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Protocol

import numpy as np
import trimesh

from .checks import overhang_area_mm2
from .settings import Constraints, SlicingSettings

log = logging.getLogger("aakar.inspect.estimate")


class SlicerBackend(Protocol):
    method: str

    def estimate(
        self, mesh: trimesh.Trimesh, slicing: SlicingSettings, constraints: Constraints | None = None
    ) -> dict[str, Any]:
        """Return a ``print-estimate.v1`` dict."""


class SlicerError(RuntimeError):
    """The slicer CLI failed or produced unparseable output."""


# --------------------------------------------------------------------------- heuristic


@dataclass(frozen=True)
class HeuristicEstimator:
    """Closed-form FDM estimate.

    Volume model
      walls   = surface area × walls × line width (capped at the solid volume)
      infill  = (solid volume − walls) × infill %
      skins   = near-horizontal surface area × skin thickness × (1 − infill %) (top/bottom solid layers)
    Time model
      perimeters are printed slower than infill, so the two volumes get their own volumetric rates
      (defaults 3.6 and 8.0 mm³/s; the blend for a typical 15 % infill part is ≈ 5.5 mm³/s at 0.2 mm
      layers including travel), plus a per-layer overhead and a fixed setup (heating, purge, homing).
    """

    method: str = "heuristic"
    wall_rate_mm3_s: float = 3.6
    infill_rate_mm3_s: float = 8.0
    layer_overhead_s: float = 1.2
    setup_s: float = 90.0
    skin_layers: int = 4
    supports_area_threshold_mm2: float = 500.0  # 5 cm² of steep overhang before we hint at supports (arch tops within one wall thickness print as short bridges)

    def estimate(
        self, mesh: trimesh.Trimesh, slicing: SlicingSettings, constraints: Constraints | None = None
    ) -> dict[str, Any]:
        constraints = constraints or Constraints()
        volume = float(abs(mesh.volume))
        area = float(mesh.area)
        line = slicing.line_width_mm
        infill_frac = slicing.infill_pct / 100.0

        wall_volume = min(area * slicing.walls * line, volume)
        interior = max(volume - wall_volume, 0.0)
        infill_volume = interior * infill_frac

        normals = np.asarray(mesh.face_normals)
        horizontal_area = float(np.asarray(mesh.area_faces)[np.abs(normals[:, 2]) > math.cos(math.radians(45))].sum())
        skin_thickness = self.skin_layers * slicing.layer_height_mm
        skin_volume = min(horizontal_area * skin_thickness * (1.0 - infill_frac), max(interior - infill_volume, 0.0))

        extruded_mm3 = wall_volume + infill_volume + skin_volume
        height = float(mesh.extents[2]) if len(mesh.faces) else 0.0
        layers = int(math.ceil(height / slicing.layer_height_mm)) if height > 0 else 0

        seconds = (
            wall_volume / self.wall_rate_mm3_s
            + (infill_volume + skin_volume) / self.infill_rate_mm3_s
            + layers * self.layer_overhead_s
            + self.setup_s
        )
        overhang = overhang_area_mm2(mesh, constraints.max_overhang_deg, slicing.layer_height_mm)
        return {
            "method": self.method,
            "print_seconds": int(round(seconds)),
            "extruded_volume_cm3": round(extruded_mm3 / 1000.0, 3),
            "layer_height_mm": slicing.layer_height_mm,
            "infill_pct": slicing.infill_pct,
            "layers": layers,
            "supports_required": bool(overhang > self.supports_area_threshold_mm2),
        }


# --------------------------------------------------------------------------- PrusaSlicer CLI

_TIME_RE = re.compile(r";\s*estimated printing time \(normal mode\)\s*=\s*(.+)")
_FILAMENT_CM3_RE = re.compile(r";\s*filament used \[cm3\]\s*=\s*([0-9.]+)")
_FILAMENT_MM_RE = re.compile(r";\s*filament used \[mm\]\s*=\s*([0-9.]+)")
_VERSION_RE = re.compile(r";\s*generated by (PrusaSlicer|OrcaSlicer|SuperSlicer)\s+([0-9][\w.+-]*)")
_DURATION_PART = re.compile(r"(\d+)\s*([dhms])")
_CONFIG_RE = re.compile(r"^;\s*([a-z_]+)\s*=\s*(.*)$", re.MULTILINE)


def parse_duration(text: str) -> int:
    """'3h 40m 12s' | '1d 2h 3m 4s' | '45m 3s' -> seconds."""
    factors = {"d": 86400, "h": 3600, "m": 60, "s": 1}
    parts = _DURATION_PART.findall(text)
    if not parts:
        raise SlicerError(f"unparseable duration: {text!r}")
    return sum(int(n) * factors[u] for n, u in parts)


def parse_gcode_footer(gcode: str, filament_diameter_mm: float = 1.75) -> dict[str, Any]:
    """Extract print time, extruded volume and a few settings from a PrusaSlicer G-code footer."""
    time_match = _TIME_RE.search(gcode)
    if not time_match:
        raise SlicerError("no '; estimated printing time (normal mode)' line in G-code")
    seconds = parse_duration(time_match.group(1).strip())

    cm3_match = _FILAMENT_CM3_RE.search(gcode)
    if cm3_match:
        volume_cm3 = float(cm3_match.group(1))
    else:
        mm_match = _FILAMENT_MM_RE.search(gcode)
        if not mm_match:
            raise SlicerError("no '; filament used [cm3]' or '[mm]' line in G-code")
        length_mm = float(mm_match.group(1))
        volume_cm3 = length_mm * math.pi * (filament_diameter_mm / 2) ** 2 / 1000.0

    config = {k: v.strip() for k, v in _CONFIG_RE.findall(gcode)}
    out: dict[str, Any] = {"print_seconds": int(seconds), "extruded_volume_cm3": round(volume_cm3, 3)}
    version = _VERSION_RE.search(gcode)
    if version:
        out["slicer_version"] = f"{version.group(1)} {version.group(2)}"
    if "layer_height" in config:
        try:
            out["layer_height_mm"] = float(config["layer_height"])
        except ValueError:
            pass
    if "fill_density" in config:
        try:
            out["infill_pct"] = float(config["fill_density"].rstrip("%"))
        except ValueError:
            pass
    if "support_material" in config:
        out["supports_required"] = config["support_material"] in ("1", "true")
    return out


@dataclass(frozen=True)
class PrusaSlicerCli:
    """Slice with a PrusaSlicer-compatible CLI and read the footer. Mesh must be mm, Z-up."""

    binary: str
    method: str = "prusaslicer_cli"
    timeout_s: float = 600.0
    filament_diameter_mm: float = 1.75

    def write_config(self, path: Path, slicing: SlicingSettings, supports: bool) -> None:
        lines = [
            f"layer_height = {slicing.layer_height_mm}",
            f"first_layer_height = {slicing.layer_height_mm}",
            f"fill_density = {slicing.infill_pct:g}%",
            "fill_pattern = grid",
            f"perimeters = {slicing.walls}",
            f"nozzle_diameter = {slicing.nozzle_mm}",
            f"extrusion_width = {slicing.line_width_mm}",
            "top_solid_layers = 4",
            "bottom_solid_layers = 4",
            f"filament_diameter = {self.filament_diameter_mm}",
            f"support_material = {1 if supports else 0}",
            "support_material_auto = 1",
            "skirts = 1",
            "gcode_flavor = marlin2",
            "gcode_comments = 0",
        ]
        for key, value in slicing.extra.items():
            lines.append(f"{key} = {value}")
        path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    def estimate(
        self, mesh: trimesh.Trimesh, slicing: SlicingSettings, constraints: Constraints | None = None
    ) -> dict[str, Any]:
        constraints = constraints or Constraints()
        supports = overhang_area_mm2(mesh, constraints.max_overhang_deg, slicing.layer_height_mm) > 500.0
        with tempfile.TemporaryDirectory(prefix="aakar-slice-") as tmp:
            tmp_path = Path(tmp)
            stl = tmp_path / "model.stl"
            ini = tmp_path / "config.ini"
            gcode = tmp_path / "model.gcode"
            mesh.export(stl)
            self.write_config(ini, slicing, supports)
            cmd = [self.binary, "--export-gcode", "--load", str(ini), "--output", str(gcode), str(stl)]
            try:
                proc = subprocess.run(cmd, capture_output=True, text=True, timeout=self.timeout_s, check=False)
            except (OSError, subprocess.TimeoutExpired) as exc:
                raise SlicerError(f"slicer failed to run: {exc}") from exc
            if proc.returncode != 0 or not gcode.exists():
                raise SlicerError(f"slicer exited {proc.returncode}: {proc.stderr[-2000:]}")
            # The summary lives in the last ~64 KiB of the file.
            with gcode.open("rb") as fh:
                fh.seek(0, os.SEEK_END)
                size = fh.tell()
                fh.seek(max(0, size - 65536))
                footer = fh.read().decode("utf-8", errors="replace")
            with gcode.open("r", encoding="utf-8", errors="replace") as fh:
                head = fh.readline()
        parsed = parse_gcode_footer(head + footer, self.filament_diameter_mm)
        height = float(mesh.extents[2])
        return {
            "method": self.method,
            **({"slicer_version": parsed["slicer_version"]} if "slicer_version" in parsed else {}),
            "print_seconds": parsed["print_seconds"],
            "extruded_volume_cm3": parsed["extruded_volume_cm3"],
            "layer_height_mm": parsed.get("layer_height_mm", slicing.layer_height_mm),
            "infill_pct": parsed.get("infill_pct", slicing.infill_pct),
            "layers": int(math.ceil(height / slicing.layer_height_mm)),
            "supports_required": bool(parsed.get("supports_required", supports)),
        }


def default_backend() -> SlicerBackend:
    """PrusaSlicerCli when ``AAKAR_SLICER_BIN`` names an existing binary, else the heuristic."""
    binary = os.environ.get("AAKAR_SLICER_BIN", "").strip()
    if binary:
        resolved = binary if Path(binary).exists() else shutil.which(binary)
        if resolved:
            return PrusaSlicerCli(binary=resolved)
        log.warning("AAKAR_SLICER_BIN=%s not found; falling back to the heuristic estimator", binary)
    return HeuristicEstimator()
