import os
import stat
import sys
import textwrap
from pathlib import Path

import pytest
import trimesh

from aakar_inspect import HeuristicEstimator, PrusaSlicerCli, SlicerError, SlicingSettings, default_backend, parse_gcode_footer
from aakar_inspect.contracts import validate
from aakar_inspect.estimate import parse_duration

SAMPLE_FOOTER = textwrap.dedent(
    """\
    ; generated by PrusaSlicer 2.8.1+linux-x64-GTK3 on 2026-09-26 at 10:00:00 UTC
    G1 X10 Y10 E0.5
    ; filament used [mm] = 17203.84
    ; filament used [cm3] = 41.37
    ; filament used [g] = 51.30
    ; filament cost = 1.23
    ; total filament used [g] = 51.30
    ; total filament cost = 1.23
    ; estimated printing time (normal mode) = 3h 40m 12s
    ; estimated printing time (silent mode) = 4h 2m 1s

    ; prusaslicer_config = begin
    ; layer_height = 0.2
    ; fill_density = 15%
    ; perimeters = 3
    ; support_material = 0
    ; prusaslicer_config = end
    """
)


def test_parse_duration_forms():
    assert parse_duration("3h 40m 12s") == 3 * 3600 + 40 * 60 + 12
    assert parse_duration("1d 2h 3m 4s") == 86400 + 2 * 3600 + 3 * 60 + 4
    assert parse_duration("45m 3s") == 45 * 60 + 3
    assert parse_duration("59s") == 59
    with pytest.raises(SlicerError):
        parse_duration("soon")


def test_parse_gcode_footer_sample():
    parsed = parse_gcode_footer(SAMPLE_FOOTER)
    assert parsed["print_seconds"] == 13212
    assert parsed["extruded_volume_cm3"] == pytest.approx(41.37)
    assert parsed["slicer_version"].startswith("PrusaSlicer 2.8.1")
    assert parsed["layer_height_mm"] == 0.2
    assert parsed["infill_pct"] == 15
    assert parsed["supports_required"] is False


def test_parse_gcode_footer_falls_back_to_length():
    text = "; filament used [mm] = 1000.0\n; estimated printing time (normal mode) = 10m 0s\n"
    parsed = parse_gcode_footer(text)
    # 1000 mm of 1.75 mm filament = pi * 0.875^2 * 1000 mm^3 = 2.405 cm^3
    assert parsed["extruded_volume_cm3"] == pytest.approx(2.405, abs=0.001)
    with pytest.raises(SlicerError):
        parse_gcode_footer("; nothing useful here")


def test_heuristic_monotonic_in_volume():
    estimator = HeuristicEstimator()
    previous = None
    for size in (20, 30, 40, 60, 80):
        cube = trimesh.creation.box(extents=[size, size, size])
        cube.apply_translation([0, 0, size / 2])
        estimate = estimator.estimate(cube, SlicingSettings())
        validate("print-estimate", estimate)
        if previous is not None:
            assert estimate["extruded_volume_cm3"] > previous["extruded_volume_cm3"]
            assert estimate["print_seconds"] > previous["print_seconds"]
        assert estimate["extruded_volume_cm3"] <= size**3 / 1000 + 1e-6
        assert estimate["layers"] == size / 0.2
        previous = estimate


def test_heuristic_infill_changes_volume_not_walls():
    cube = trimesh.creation.box(extents=[60, 60, 60])
    cube.apply_translation([0, 0, 30])
    sparse = HeuristicEstimator().estimate(cube, SlicingSettings(infill_pct=10))
    dense = HeuristicEstimator().estimate(cube, SlicingSettings(infill_pct=50))
    assert dense["extruded_volume_cm3"] > sparse["extruded_volume_cm3"]
    assert dense["print_seconds"] > sparse["print_seconds"]


def test_default_backend_env(monkeypatch, tmp_path):
    monkeypatch.delenv("AAKAR_SLICER_BIN", raising=False)
    assert isinstance(default_backend(), HeuristicEstimator)
    monkeypatch.setenv("AAKAR_SLICER_BIN", str(tmp_path / "does-not-exist"))
    assert isinstance(default_backend(), HeuristicEstimator)
    fake = tmp_path / "prusa-slicer"
    fake.write_text("#!/bin/sh\nexit 1\n")
    fake.chmod(fake.stat().st_mode | stat.S_IEXEC)
    monkeypatch.setenv("AAKAR_SLICER_BIN", str(fake))
    backend = default_backend()
    assert isinstance(backend, PrusaSlicerCli)
    assert backend.binary == str(fake)


@pytest.mark.skipif(sys.platform.startswith("win"), reason="shell fake needs a POSIX shell")
def test_prusaslicer_cli_wrapper_with_fake_binary(tmp_path):
    """A stand-in 'slicer' that writes a canned footer exercises the config + parse path."""
    fake = tmp_path / "fake-slicer.py"
    fake.write_text(
        textwrap.dedent(
            f"""\
            #!{sys.executable}
            import sys
            args = sys.argv[1:]
            assert "--export-gcode" in args and "--load" in args and "--output" in args, args
            ini = open(args[args.index("--load") + 1]).read()
            assert "layer_height = 0.2" in ini and "perimeters = 3" in ini and "fill_density = 15%" in ini, ini
            open(args[args.index("--output") + 1], "w").write({SAMPLE_FOOTER!r})
            """
        )
    )
    fake.chmod(fake.stat().st_mode | stat.S_IEXEC)
    cube = trimesh.creation.box(extents=[40, 40, 40])
    cube.apply_translation([0, 0, 20])
    estimate = PrusaSlicerCli(binary=str(fake)).estimate(cube, SlicingSettings())
    validate("print-estimate", estimate)
    assert estimate["method"] == "prusaslicer_cli"
    assert estimate["print_seconds"] == 13212
    assert estimate["extruded_volume_cm3"] == pytest.approx(41.37)
    assert estimate["layers"] == 200
    assert estimate["slicer_version"].startswith("PrusaSlicer")
