/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Staff sign-in */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Signed in */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StaffSession"];
                    };
                };
                401: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Staff member */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Staff"];
                    };
                };
                401: components["responses"]["Problem"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Counts and money for the studio board */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Dashboard */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            orders_by_status: {
                                [key: string]: number;
                            };
                            orders_today: number;
                            revenue_today_paise: number;
                            revenue_month_paise: number;
                            /** @description Orders in queued, finishing or qc that need a staff step */
                            awaiting_action: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Orders queue */
        get: {
            parameters: {
                query?: {
                    /** @description Comma-separated OrderStatus values */
                    status?: string;
                    /** @description Order number or customer phone */
                    q?: string;
                    page?: number;
                    size?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Page of orders */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["AdminOrderSummary"][];
                            page: number;
                            size: number;
                            total: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/orders/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderId: components["parameters"]["OrderId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Order */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminOrder"];
                    };
                };
                404: components["responses"]["Problem"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/orders/{orderId}/advance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Move the order to its next status
         * @description Allowed transitions: confirmed→queued→slicing→printing→finishing→qc→packed→shipped→delivered; any active status→on_hold and back to the previous status; qc→reprint→printing; any status before shipped→cancelled. Packed creates the shipment; shipped adds the carrier event. Invalid moves answer 409 invalid_transition.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderId: components["parameters"]["OrderId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        status: components["schemas"]["OrderStatus"];
                        /** @description Shown to the customer on the tracking page */
                        message?: string;
                        /** @description Free-form; the tracking board reads studio, printer_bay, layer_height_mm, layers_total, layer */
                        detail?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            responses: {
                /** @description Order after the move */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminOrder"];
                    };
                };
                404: components["responses"]["Problem"];
                /** @description invalid_transition */
                409: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/orders/{orderId}/print-pack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Everything the outsourced printer needs, as one zip
         * @description Per item: model.3mf and model.stl (from the version's assets), plus print-sheet.txt (order number, item, material and filament, quantity, finish class, dimensions, mass, estimated time, notes). Printing is outsourced for now (ADR-0004).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderId: components["parameters"]["OrderId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Zip archive */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/zip": string;
                    };
                };
                404: components["responses"]["Problem"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/orders/{orderId}/qc-photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Attach a QC photo */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderId: components["parameters"]["OrderId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file: string;
                        note?: string;
                    };
                };
            };
            responses: {
                /** @description Stored */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MediaAsset"];
                    };
                };
                404: components["responses"]["Problem"];
                /** @description Larger than 10 MB */
                413: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/orders/{orderId}/packaging-card.pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The card that goes in the box
         * @description "Designed by You. Crafted by Aakar." with piece, finish, studio, date and the /k/{code} link (QR + text). Available from packed onwards.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderId: components["parameters"]["OrderId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description PDF */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/pdf": string;
                    };
                };
                404: components["responses"]["Problem"];
                /** @description Not packed yet (order_not_packed) */
                409: components["responses"]["Problem"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/pricing/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All pricing policy versions, newest first */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Policies */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PricingPolicyVersion"][];
                    };
                };
            };
        };
        put?: never;
        /** Publish a new policy version (becomes active) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        version: string;
                        policy: components["schemas"]["PricingPolicy"];
                        note?: string;
                    };
                };
            };
            responses: {
                /** @description Published */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PricingPolicyVersion"];
                    };
                };
                403: components["responses"]["Problem"];
                /** @description policy_version_exists */
                409: components["responses"]["Problem"];
                422: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/pricing/policies/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Active policy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PricingPolicyVersion"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/pricing/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** What would a piece cost under a draft policy */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        policy: components["schemas"]["PricingPolicy"];
                        material: string;
                        extruded_volume_cm3: number;
                        print_seconds: number;
                        /** @description Applies the family's hardware default, setup fee and minimum */
                        family_id?: string;
                    };
                };
            };
            responses: {
                /** @description Breakdown */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["price-breakdown.v1"];
                    };
                };
                422: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/materials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Materials incl. unavailable */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminMaterial"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminMaterialInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminMaterial"];
                    };
                };
                403: components["responses"]["Problem"];
                /** @description material_exists */
                409: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/materials/{materialId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    materialId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminMaterialInput"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminMaterial"];
                    };
                };
                403: components["responses"]["Problem"];
                404: components["responses"]["Problem"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/catalog/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description All items incl. unavailable */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CatalogItem"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CatalogItemInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CatalogItem"];
                    };
                };
                403: components["responses"]["Problem"];
                /** @description slug_exists */
                409: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/catalog/items/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CatalogItemInput"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CatalogItem"];
                    };
                };
                403: components["responses"]["Problem"];
                404: components["responses"]["Problem"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/catalog/shelves": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Shop shelves in display order */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Shelves */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Shelf"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/families": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every outcome family (Avatar), available or not, with readiness */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Families */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminFamily"][];
                    };
                };
            };
        };
        put?: never;
        /** Create a family (owner only, audited as family.create) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminFamilyInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminFamily"];
                    };
                };
                403: components["responses"]["Problem"];
                /** @description family_exists */
                409: components["responses"]["Problem"];
                422: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/families/{familyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update a family's copy, tier, shelf, envelope, hardware, rules, content slot or availability (owner only, audited as family.update) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    familyId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminFamilyInput"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminFamily"];
                    };
                };
                403: components["responses"]["Problem"];
                /** @description unknown_family */
                404: components["responses"]["Problem"];
                422: components["responses"]["Problem"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/hardware": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bought-in hardware items */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Hardware */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminHardware"][];
                    };
                };
            };
        };
        put?: never;
        /** Create a hardware item (owner only, audited as hardware.create) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminHardwareInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminHardware"];
                    };
                };
                403: components["responses"]["Problem"];
                /** @description hardware_exists */
                409: components["responses"]["Problem"];
                422: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/hardware/{sku}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update a hardware item (owner only, audited as hardware.update) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sku: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminHardwareInput"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminHardware"];
                    };
                };
                403: components["responses"]["Problem"];
                404: components["responses"]["Problem"];
                422: components["responses"]["Problem"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/experiences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every experience (Duniya), available or not, in display order
         * @description Rows as stored, for the portal's Duniya page: `avatars` are family ids and `items` Shop item slugs, in order.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Experiences */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminExperience"][];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create an experience (owner only, audited as experience.create)
         * @description 409 `experience_exists` for a taken id, 409 `slug_exists` for a taken slug. 422 `validation_failed` for a schema
         *     violation, an environment that is not in GET /admin/api/environments (the detail names the known ones), an unknown
         *     Shop item slug, a repeated avatar, item or motif, or a season window whose ends are not both dates (in order) or both
         *     month-days; 422 `unknown_family` for an avatar that is not a family.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminExperienceInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminExperience"];
                    };
                };
                403: components["responses"]["Problem"];
                /** @description experience_exists or slug_exists */
                409: components["responses"]["Problem"];
                /** @description validation_failed or unknown_family */
                422: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/experiences/{experienceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update an experience's copy, slug, backdrop, style, motif pack, avatars, items, collections, seasons or availability (owner only, audited as experience.update)
         * @description The id in the path wins over the body. 404 `unknown_experience`; 409 `slug_exists` when another experience has the slug; 422 as on create.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    experienceId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminExperienceInput"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminExperience"];
                    };
                };
                403: components["responses"]["Problem"];
                /** @description unknown_experience */
                404: components["responses"]["Problem"];
                /** @description slug_exists */
                409: components["responses"]["Problem"];
                /** @description validation_failed or unknown_family */
                422: components["responses"]["Problem"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/environments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Viewer backdrops (Mahaul) in display order, read-only reference data
         * @description The valid `environment` values for experiences, families and Shop items. New backdrops need a storefront preset first (engineering).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Environments */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Environment"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Customer uploads, newest first (filter by status for the review queue) */
        get: {
            parameters: {
                query?: {
                    status?: "ready" | "pending_review" | "rejected";
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Uploads */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminUpload"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/content-reviews/{reviewId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decide a flagged upload (studio or owner, audited as review.decide) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    reviewId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ContentReviewDecision"];
                };
            };
            responses: {
                /** @description Decided */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminUpload"];
                    };
                };
                404: components["responses"]["Problem"];
                /** @description review_already_decided */
                409: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Templates known to the geometry service with their live flag */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Templates */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            version: number;
                            family: string;
                            name: string;
                            /** @description False hides the template from Create and blocks new designs */
                            live: boolean;
                            /** @description Slugs using this template */
                            catalog_items?: string[];
                            /** @description Chhaap types the template accepts */
                            features_supported?: ("emboss_text" | "motif" | "relief_image" | "hero_mesh")[];
                            /** @description Bought-in parts the template is cut for */
                            hardware?: components["schemas"]["HardwareRef"][];
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/templates/{templateId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    templateId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        live: boolean;
                    };
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                403: components["responses"]["Problem"];
                404: components["responses"]["Problem"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Messages log (what the mock sender would have sent) */
        get: {
            parameters: {
                query?: {
                    order_id?: string;
                    page?: number;
                    size?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Page of messages */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["NotificationRecord"][];
                            page: number;
                            size: number;
                            total: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    page?: number;
                    size?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Page of audit entries */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["AuditEntry"][];
                            page: number;
                            size: number;
                            total: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Staff: {
            /** Format: uuid */
            id: string;
            email: string;
            name: string;
            /** @enum {string} */
            role: "owner" | "studio";
        };
        StaffSession: {
            access_token: string;
            /** @constant */
            token_type: "Bearer";
            expires_in_s: number;
            staff: components["schemas"]["Staff"];
        };
        AdminOrderSummary: components["schemas"]["OrderSummary"] & {
            customer: {
                /** Format: uuid */
                id?: string;
                phone?: string;
                name?: string | null;
            };
            materials?: string[];
            /** @description Statuses this order may be advanced to */
            next_actions?: components["schemas"]["OrderStatus"][];
        };
        AdminOrder: components["schemas"]["Order"] & {
            customer: {
                /** Format: uuid */
                id?: string;
                phone?: string;
                name?: string | null;
                email?: string | null;
            };
            next_actions: components["schemas"]["OrderStatus"][];
            qc_photos?: components["schemas"]["MediaAsset"][];
            notifications?: components["schemas"]["NotificationRecord"][];
        };
        MediaAsset: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            kind: "qc_photo" | "packaging_card" | "other";
            url: string;
            content_type: string;
            bytes: number;
            note?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        /** @description Same shape as design-tokens materials.json pricing_policy, minus the version. */
        PricingPolicy: {
            machine_rate_paise_per_hour: number;
            /** @description Keyed by finish class (matte */
            finishing_fee_paise: {
                [key: string]: number;
            };
            packaging_fee_paise: number;
            margin_pct: number;
            round_to_rupees_ending_in: number;
            shipping_flat_paise: number;
            free_shipping_above_paise: number;
            shipping_label: string;
            /** @description Applied to bought-in hardware unit costs; 0 when absent */
            hardware_markup_pct?: number;
            /** @description Per-outcome rules keyed by family id */
            family_rules?: {
                [key: string]: {
                    /** @description Lifts the subtotal to at least this (rounded to the policy ending) */
                    minimum_subtotal_paise?: number;
                    /** @description Studio setup line, e.g. repair and orientation labour for raw prints */
                    setup_fee_paise?: number;
                    qty_breaks?: {
                        min_qty: number;
                        discount_pct: number;
                    }[];
                };
            };
        };
        PricingPolicyVersion: {
            version: string;
            active: boolean;
            policy: components["schemas"]["PricingPolicy"];
            note?: string | null;
            /** Format: date-time */
            created_at: string;
            /** @description Staff email or system */
            created_by: string;
        };
        AdminMaterialInput: {
            id: string;
            name: string;
            filament: string;
            density_g_cm3: number;
            /** @enum {string} */
            finish_class: "matte" | "silk";
            rate_per_g_paise: number;
            /** @default false */
            heat_safe: boolean;
            /** @default true */
            available: boolean;
            /** @default 100 */
            sort_order: number;
            pbr: components["schemas"]["pbr"];
        };
        AdminMaterial: components["schemas"]["AdminMaterialInput"] & {
            /** Format: date-time */
            updated_at?: string;
        };
        CatalogItemInput: {
            slug: string;
            name: string;
            /** @description A shelf id from GET /admin/api/catalog/shelves; 422 validation_failed otherwise */
            category: string;
            /** @description Outcome family (Avatar); 422 unknown_family when not seeded */
            family_id?: string | null;
            description?: string;
            template_id: string;
            default_params: {
                [key: string]: unknown;
            };
            default_material: string;
            base_price_paise: number;
            specs_line: string;
            /** @description An environment id from GET /admin/api/environments; 422 validation_failed otherwise */
            environment?: string | null;
            available: boolean;
            media?: {
                kind?: string;
                url?: string;
            }[];
        };
        /** @description Same fields as schemas/template-family.v1.json#/$defs/family. On PUT the id in the path wins. */
        AdminFamilyInput: {
            id: string;
            codename: string;
            name: string;
            tagline?: string;
            description?: string;
            /** @enum {string} */
            kind: "carrier" | "object" | "raw";
            /** @enum {string} */
            tier: "launch" | "next" | "later";
            shelf: string;
            demand_rank?: number;
            default_template_id: string;
            /** @description An environment id from GET /admin/api/environments (studio when absent); 422 validation_failed otherwise */
            environment?: string;
            size_envelope_mm?: {
                min_longest_mm: number;
                max_longest_mm: number;
            };
            hardware?: {
                sku: string;
                qty: number;
            }[];
            material_rules?: {
                heat_safe_only?: boolean;
                allowed?: string[] | null;
                excluded_finish_classes?: ("matte" | "silk")[];
            };
            /** @enum {string} */
            shape_tolerance: "any" | "constrained" | "strict";
            content_slot: {
                accepts: ("emboss_text" | "motif" | "relief_image" | "hero_mesh")[];
                anchors?: string[];
                hero_volume?: boolean;
                max_text_chars?: number;
            };
            available: boolean;
            /** @default 100 */
            sort_order: number;
        };
        AdminFamily: components["schemas"]["AdminFamilyInput"] & {
            /** @description At least one live template of this family exists */
            ready: boolean;
            template_ids?: string[];
            /** Format: date-time */
            updated_at?: string;
        };
        AdminHardwareInput: {
            sku: string;
            name: string;
            unit_cost_paise: number;
            weight_g?: number;
            supplier?: string;
            url?: string;
            notes?: string;
            /** @default true */
            available: boolean;
        };
        AdminHardware: components["schemas"]["AdminHardwareInput"] & {
            /** Format: date-time */
            updated_at?: string;
        };
        /** @description Same fields as schemas/experience.v1.json#/$defs/experience. On PUT the id in the path wins. */
        AdminExperienceInput: {
            /** @description snake_case English, never renamed (festive, desk_gaming, …) */
            id: string;
            /** @description Brand name, e.g. Utsav */
            codename: string;
            /** @description URL slug (/duniya/<slug>) */
            slug: string;
            /** @description Plain descriptor, e.g. Festive & gifting */
            title: string;
            tagline?: string;
            description?: string;
            /** @description An environment id from GET /admin/api/environments */
            environment: string;
            surface: components["schemas"]["ExperienceSurface"];
            /**
             * @default none
             * @enum {string}
             */
            style: "none" | "jaipur_heritage" | "modern_zen" | "cyber_desi" | "warli_line" | "comic_pop";
            /** @description Motif ids (or a pack id) offered first, in order */
            motif_pack?: string[];
            /** @description Family ids in display order */
            avatars: string[];
            /** @description Shop item slugs in display order */
            items?: string[];
            collections?: components["schemas"]["ExperienceCollection"][];
            season?: components["schemas"]["SeasonWindow"][];
            available: boolean;
            /** @default 100 */
            sort_order: number;
        };
        AdminExperience: components["schemas"]["AdminExperienceInput"] & {
            /** Format: date-time */
            updated_at?: string;
        };
        AdminUpload: components["schemas"]["Upload"] & {
            owner?: {
                /** Format: uuid */
                user_id?: string | null;
                /** Format: uuid */
                guest_id?: string | null;
                phone?: string | null;
            };
            /** @description Staff get the file URL in every status so reviewers can see it */
            url?: string | null;
            /** @enum {string} */
            origin?: "upload" | "generated";
            review?: {
                /** Format: uuid */
                id?: string;
                reason?: string;
                /** @enum {string} */
                status?: "pending" | "approved" | "rejected";
                decision_note?: string | null;
                reviewer_email?: string | null;
                /** Format: date-time */
                decided_at?: string | null;
            } | null;
        };
        ContentReviewDecision: {
            /** @enum {string} */
            decision: "approved" | "rejected";
            note?: string;
        };
        NotificationRecord: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            order_id?: string | null;
            /** Format: uuid */
            user_id?: string | null;
            /** @enum {string} */
            channel: "whatsapp" | "email" | "sms";
            /** @description order_confirmed */
            template: string;
            to: string;
            payload?: {
                [key: string]: unknown;
            };
            /** @description What the mock would have sent */
            rendered_text?: string | null;
            /** @enum {string} */
            status: "logged" | "sent" | "failed";
            /** Format: date-time */
            created_at: string;
        };
        AuditEntry: {
            id: number;
            /** Format: date-time */
            at: string;
            staff_email: string;
            /** @description order.advance, pricing.publish, material.update, catalog.update, template.live, family.create, family.update, hardware.create, hardware.update, experience.create, experience.update, review.decide */
            action: string;
            /** @description Order number, policy version, material id, slug, template id, family id, hardware sku, experience id or review id */
            target: string;
            before?: {
                [key: string]: unknown;
            } | null;
            after?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * @description Internal status. The customer stage is derived.
         * @enum {string}
         */
        OrderStatus: "pending_payment" | "confirmed" | "queued" | "slicing" | "printing" | "finishing" | "qc" | "packed" | "shipped" | "delivered" | "cancelled" | "on_hold" | "reprint";
        /**
         * @description Customer-facing collapsed stage (board 06).
         * @enum {string}
         */
        OrderStage: "payment" | "queued" | "slicing" | "printing" | "sanding" | "shipped" | "delivered" | "cancelled";
        OrderSummary: {
            /** Format: uuid */
            id: string;
            /** @description AK-000001 */
            number: string;
            status: components["schemas"]["OrderStatus"];
            stage: components["schemas"]["OrderStage"];
            /** @description First item title plus a count of the others */
            title?: string;
            total_paise: number;
            items_count: number;
            /** Format: date */
            eta?: string | null;
            /** Format: date-time */
            placed_at: string;
        };
        /**
         * Aakar Price Breakdown v1
         * @description Computed by the API pricing module from a print estimate and a material. All amounts are integer paise (INR minor units). Snapshotted into cart and order so totals never drift.
         */
        "price-breakdown.v1": {
            /** @constant */
            currency: "INR";
            material_id: string;
            mass_g: number;
            print_seconds: number;
            lines: {
                /** @enum {string} */
                code: "material" | "machine_time" | "finishing" | "packaging" | "hardware" | "setup";
                /** @description Customer-facing, e.g. 'Material · 84 g' or 'Print time · 3 h 40 m'. */
                label: string;
                detail?: string;
                amount_paise: number;
            }[];
            /** @description Sum of lines with margin applied and rounded to a price ending in 9 rupees. */
            subtotal_paise: number;
            /** @description 0 when free. */
            shipping_paise: number;
            shipping_label?: string;
            total_paise: number;
            policy_version: string;
            /** @description Outcome family the piece belongs to, when known; drives hardware, setup and minimum rules. */
            family_id?: string;
            /** @description Present when the family's minimum lifted the subtotal above the computed lines. */
            minimum_subtotal_paise?: number;
        };
        OrderItem: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            design_id: string;
            /** Format: uuid */
            version_id: string;
            version_no?: number;
            title: string;
            specs_line?: string;
            material_id: string;
            material_name?: string;
            qty: number;
            unit_price: components["schemas"]["price-breakdown.v1"];
            line_total_paise: number;
            /** @description Snapshot of the version assets at order time */
            assets?: {
                [key: string]: unknown;
            };
        };
        AddressInput: {
            /** @description Home or Office */
            label?: string;
            name: string;
            phone: string;
            line1: string;
            line2?: string;
            city: string;
            state: string;
            pincode: string;
            /** @default false */
            is_default: boolean;
        };
        Address: components["schemas"]["AddressInput"] & {
            /** Format: uuid */
            id: string;
        };
        Payment: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            order_id: string;
            /** @description mock or razorpay */
            gateway: string;
            /** @description Provider order or payment id */
            gateway_ref?: string | null;
            /** @enum {string} */
            status: "created" | "pending" | "succeeded" | "failed" | "refunded";
            method?: string | null;
            amount_paise: number;
            /** @constant */
            currency: "INR";
            /** @description Where the customer pays; the placeholder page for the mock gateway */
            pay_url?: string | null;
            invoice_number?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            finished_at?: string | null;
        };
        Shipment: {
            /** Format: uuid */
            id: string;
            carrier: string;
            awb?: string | null;
            /** @enum {string} */
            status: "created" | "picked_up" | "in_transit" | "out_for_delivery" | "delivered" | "returned";
            /** Format: date */
            eta?: string | null;
            tracking_url?: string | null;
            events?: {
                status?: string;
                message?: string;
                /** Format: date-time */
                at?: string;
            }[];
        };
        OrderEvent: {
            sequence: number;
            status: components["schemas"]["OrderStatus"];
            stage: components["schemas"]["OrderStage"];
            message: string;
            /** @description Studio, printer bay and layer height for the tracking board */
            detail?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            at: string;
        };
        Order: components["schemas"]["OrderSummary"] & {
            items: components["schemas"]["OrderItem"][];
            address: components["schemas"]["Address"];
            subtotal_paise: number;
            shipping_paise: number;
            shipping_label?: string;
            policy_version?: string;
            payment: components["schemas"]["Payment"];
            shipment?: components["schemas"]["Shipment"];
            events: components["schemas"]["OrderEvent"][];
            notify_whatsapp?: boolean;
            note?: string | null;
        };
        pbr: {
            /** @description sRGB hex */
            color: string;
            roughness: number;
            metalness: number;
            clearcoat?: number;
            clearcoat_roughness?: number;
            sheen?: number;
            sheen_color?: string;
        };
        CatalogItem: {
            slug: string;
            /** @description False until the item's template exists in the geometry service; the Shop shows a 'Coming soon' ribbon and POST /api/designs answers 422 template_not_available. */
            available: boolean;
            name: string;
            /** @description A shelf id from GET /api/catalog/shelves */
            category: string;
            /** @description Outcome family (Avatar) of the item's template, when known */
            family_id?: string | null;
            description?: string;
            template_id: string;
            default_params: {
                [key: string]: unknown;
            };
            default_material: string;
            base_price_paise: number;
            /** @description e.g. 'Fits phones to 6.9″ · 92 × 78 × 120 mm · 64 g' */
            specs_line: string;
            /** @description Viewer backdrop, an environment id from GET /api/environments */
            environment?: string;
            media?: {
                kind?: string;
                url?: string;
            }[];
        };
        Shelf: {
            id: string;
            label: string;
            sort_order: number;
        };
        /** @description Page theming of an experience. The cream paper stays; the accent and the hero change. */
        ExperienceSurface: {
            /** @description sRGB hex from the brand palette */
            accent: string;
            /** @description A light tint over the cream paper; null keeps plain cream */
            paper_tint?: string | null;
            /** @description URL or site path of the hero image or loop; null until one is shot */
            hero_media?: string | null;
        };
        /** @description A sub-collection, e.g. a licensed universe; none until a licence exists */
        ExperienceCollection: {
            id: string;
            title: string;
            /** @description The licence agreement that allows it; null for original work */
            licence_ref?: string | null;
        };
        /** @description When an experience is in season. Both ends are dates (starts_on ≤ ends_on) or both are month-days that recur every year and may wrap the new year. */
        SeasonWindow: {
            /** @description A date (2026-10-20) or an ISO month-day (--10-01) */
            starts_on: string;
            /** @description A date (2026-11-10) or an ISO month-day (--11-30) */
            ends_on: string;
            /** @description Badge text, e.g. Diwali */
            label: string;
        };
        /** @description A viewer backdrop (Mahaul). Same fields as schemas/experience.v1.json#/$defs/environment. */
        Environment: {
            id: string;
            /** @description Plain name, e.g. Chettinad teak · candlelight */
            label: string;
            /**
             * @description The surface the backdrop sits on
             * @enum {string}
             */
            surface: "stage" | "paper";
            /** @description The storefront viewer preset that renders it (src/lib/viewer/environments.ts) */
            preset_key: string;
            /** @description Swatches (sRGB hex) for thumbnails and theme previews, the backdrop colour first */
            palette?: string[];
            sort_order: number;
        };
        Upload: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            kind: "image" | "model";
            format: string;
            bytes: number;
            sha256?: string;
            /** @enum {string} */
            status: "ready" | "pending_review" | "rejected";
            /** @description Browser-fetchable URL when ready */
            url?: string | null;
            /** @description Customer-facing note, e.g. the reviewer's reason when status is rejected */
            message?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        HardwareRef: {
            sku: string;
            qty: number;
            /** @description Customer-facing hardware name, filled by the API from hardware_items */
            name?: string;
        };
    };
    responses: {
        /** @description Problem Details */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    type?: string;
                    title?: string;
                    status?: number;
                    detail?: string;
                    code?: string;
                };
            };
        };
    };
    parameters: {
        OrderId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
