/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Staff sign-in */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Signed in */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StaffSession"];
                    };
                };
                401: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Staff member */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Staff"];
                    };
                };
                401: components["responses"]["Problem"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Counts and money for the studio board */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Dashboard */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            orders_by_status: {
                                [key: string]: number;
                            };
                            orders_today: number;
                            revenue_today_paise: number;
                            revenue_month_paise: number;
                            /** @description Orders in queued */
                            awaiting_action: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Orders queue */
        get: {
            parameters: {
                query?: {
                    /** @description Comma-separated OrderStatus values */
                    status?: string;
                    /** @description Order number or customer phone */
                    q?: string;
                    page?: number;
                    size?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Page of orders */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["AdminOrderSummary"][];
                            page: number;
                            size: number;
                            total: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/orders/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderId: components["parameters"]["OrderId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Order */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminOrder"];
                    };
                };
                404: components["responses"]["Problem"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/orders/{orderId}/advance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Move the order to its next status
         * @description Allowed transitions: confirmed→queued→slicing→printing→finishing→qc→packed→shipped→delivered; any active status→on_hold and back to the previous status; qc→reprint→printing; any status before shipped→cancelled. Packed creates the shipment; shipped adds the carrier event. Invalid moves answer 409 invalid_transition.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderId: components["parameters"]["OrderId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        status: components["schemas"]["OrderStatus"];
                        /** @description Shown to the customer on the tracking page */
                        message?: string;
                        /** @description Free-form; the tracking board reads studio, printer_bay, layer_height_mm, layers_total, layer */
                        detail?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            responses: {
                /** @description Order after the move */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminOrder"];
                    };
                };
                404: components["responses"]["Problem"];
                /** @description invalid_transition */
                409: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/orders/{orderId}/print-pack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Everything the outsourced printer needs, as one zip
         * @description Per item: model.3mf and model.stl (from the version's assets), plus print-sheet.txt (order number, item, material and filament, quantity, finish class, dimensions, mass, estimated time, notes). Printing is outsourced for now (ADR-0004).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderId: components["parameters"]["OrderId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Zip archive */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/zip": string;
                    };
                };
                404: components["responses"]["Problem"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/orders/{orderId}/qc-photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Attach a QC photo */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderId: components["parameters"]["OrderId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file: string;
                        note?: string;
                    };
                };
            };
            responses: {
                /** @description Stored */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MediaAsset"];
                    };
                };
                404: components["responses"]["Problem"];
                /** @description Larger than 10 MB */
                413: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/orders/{orderId}/packaging-card.pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The card that goes in the box
         * @description "Designed by You. Crafted by Aakar." with piece, finish, studio, date and the /k/{code} link (QR + text). Available from packed onwards.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderId: components["parameters"]["OrderId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description PDF */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/pdf": string;
                    };
                };
                404: components["responses"]["Problem"];
                /** @description Not packed yet (order_not_packed) */
                409: components["responses"]["Problem"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/pricing/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All pricing policy versions, newest first */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Policies */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PricingPolicyVersion"][];
                    };
                };
            };
        };
        put?: never;
        /** Publish a new policy version (becomes active) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        version: string;
                        policy: components["schemas"]["PricingPolicy"];
                        note?: string;
                    };
                };
            };
            responses: {
                /** @description Published */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PricingPolicyVersion"];
                    };
                };
                403: components["responses"]["Problem"];
                /** @description policy_version_exists */
                409: components["responses"]["Problem"];
                422: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/pricing/policies/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Active policy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PricingPolicyVersion"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/pricing/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** What would a piece cost under a draft policy */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        policy: components["schemas"]["PricingPolicy"];
                        material: string;
                        extruded_volume_cm3: number;
                        print_seconds: number;
                    };
                };
            };
            responses: {
                /** @description Breakdown */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["price-breakdown.v1"];
                    };
                };
                422: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/materials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Materials incl. unavailable */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminMaterial"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminMaterialInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminMaterial"];
                    };
                };
                403: components["responses"]["Problem"];
                /** @description material_exists */
                409: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/materials/{materialId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    materialId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminMaterialInput"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminMaterial"];
                    };
                };
                403: components["responses"]["Problem"];
                404: components["responses"]["Problem"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/catalog/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description All items incl. unavailable */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CatalogItem"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CatalogItemInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CatalogItem"];
                    };
                };
                403: components["responses"]["Problem"];
                /** @description slug_exists */
                409: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/catalog/items/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CatalogItemInput"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CatalogItem"];
                    };
                };
                403: components["responses"]["Problem"];
                404: components["responses"]["Problem"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Templates known to the geometry service with their live flag */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Templates */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            version: number;
                            family: string;
                            name: string;
                            /** @description False hides the template from Create and blocks new designs */
                            live: boolean;
                            /** @description Slugs using this template */
                            catalog_items?: string[];
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/templates/{templateId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    templateId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        live: boolean;
                    };
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                403: components["responses"]["Problem"];
                404: components["responses"]["Problem"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Messages log (what the mock sender would have sent) */
        get: {
            parameters: {
                query?: {
                    order_id?: string;
                    page?: number;
                    size?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Page of messages */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["NotificationRecord"][];
                            page: number;
                            size: number;
                            total: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    page?: number;
                    size?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Page of audit entries */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["AuditEntry"][];
                            page: number;
                            size: number;
                            total: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Staff: {
            /** Format: uuid */
            id: string;
            email: string;
            name: string;
            /** @enum {string} */
            role: "owner" | "studio";
        };
        StaffSession: {
            access_token: string;
            /** @constant */
            token_type: "Bearer";
            expires_in_s: number;
            staff: components["schemas"]["Staff"];
        };
        AdminOrderSummary: components["schemas"]["OrderSummary"] & {
            customer: {
                /** Format: uuid */
                id?: string;
                phone?: string;
                name?: string | null;
            };
            materials?: string[];
            /** @description Statuses this order may be advanced to */
            next_actions?: components["schemas"]["OrderStatus"][];
        };
        AdminOrder: components["schemas"]["Order"] & {
            customer: {
                /** Format: uuid */
                id?: string;
                phone?: string;
                name?: string | null;
                email?: string | null;
            };
            next_actions: components["schemas"]["OrderStatus"][];
            qc_photos?: components["schemas"]["MediaAsset"][];
            notifications?: components["schemas"]["NotificationRecord"][];
        };
        MediaAsset: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            kind: "qc_photo" | "packaging_card" | "other";
            url: string;
            content_type: string;
            bytes: number;
            note?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        /** @description Same shape as design-tokens materials.json pricing_policy, minus the version. */
        PricingPolicy: {
            machine_rate_paise_per_hour: number;
            /** @description Keyed by finish class (matte */
            finishing_fee_paise: {
                [key: string]: number;
            };
            packaging_fee_paise: number;
            margin_pct: number;
            round_to_rupees_ending_in: number;
            shipping_flat_paise: number;
            free_shipping_above_paise: number;
            shipping_label: string;
        };
        PricingPolicyVersion: {
            version: string;
            active: boolean;
            policy: components["schemas"]["PricingPolicy"];
            note?: string | null;
            /** Format: date-time */
            created_at: string;
            /** @description Staff email or system */
            created_by: string;
        };
        AdminMaterialInput: {
            id: string;
            name: string;
            filament: string;
            density_g_cm3: number;
            /** @enum {string} */
            finish_class: "matte" | "silk";
            rate_per_g_paise: number;
            /** @default false */
            heat_safe: boolean;
            /** @default true */
            available: boolean;
            /** @default 100 */
            sort_order: number;
            pbr: components["schemas"]["pbr"];
        };
        AdminMaterial: components["schemas"]["AdminMaterialInput"] & {
            /** Format: date-time */
            updated_at?: string;
        };
        CatalogItemInput: {
            slug: string;
            name: string;
            /** @enum {string} */
            category: "home_decor" | "nameplates" | "kitchen" | "desk_tech" | "gifting";
            description?: string;
            template_id: string;
            default_params: {
                [key: string]: unknown;
            };
            default_material: string;
            base_price_paise: number;
            specs_line: string;
            environment?: string;
            available: boolean;
            media?: {
                kind?: string;
                url?: string;
            }[];
        };
        NotificationRecord: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            order_id?: string | null;
            /** Format: uuid */
            user_id?: string | null;
            /** @enum {string} */
            channel: "whatsapp" | "email" | "sms";
            /** @description order_confirmed */
            template: string;
            to: string;
            payload?: {
                [key: string]: unknown;
            };
            /** @description What the mock would have sent */
            rendered_text?: string | null;
            /** @enum {string} */
            status: "logged" | "sent" | "failed";
            /** Format: date-time */
            created_at: string;
        };
        AuditEntry: {
            id: number;
            /** Format: date-time */
            at: string;
            staff_email: string;
            /** @description order.advance */
            action: string;
            /** @description Order number */
            target: string;
            before?: {
                [key: string]: unknown;
            } | null;
            after?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * @description Internal status. The customer stage is derived.
         * @enum {string}
         */
        OrderStatus: "pending_payment" | "confirmed" | "queued" | "slicing" | "printing" | "finishing" | "qc" | "packed" | "shipped" | "delivered" | "cancelled" | "on_hold" | "reprint";
        /**
         * @description Customer-facing collapsed stage (board 06).
         * @enum {string}
         */
        OrderStage: "payment" | "queued" | "slicing" | "printing" | "sanding" | "shipped" | "delivered" | "cancelled";
        OrderSummary: {
            /** Format: uuid */
            id: string;
            /** @description AK-000001 */
            number: string;
            status: components["schemas"]["OrderStatus"];
            stage: components["schemas"]["OrderStage"];
            /** @description First item title plus a count of the others */
            title?: string;
            total_paise: number;
            items_count: number;
            /** Format: date */
            eta?: string | null;
            /** Format: date-time */
            placed_at: string;
        };
        /**
         * Aakar Price Breakdown v1
         * @description Computed by the API pricing module from a print estimate and a material. All amounts are integer paise (INR minor units). Snapshotted into cart and order so totals never drift.
         */
        "price-breakdown.v1": {
            /** @constant */
            currency: "INR";
            material_id: string;
            mass_g: number;
            print_seconds: number;
            lines: {
                /** @enum {string} */
                code: "material" | "machine_time" | "finishing" | "packaging";
                /** @description Customer-facing, e.g. 'Material · 84 g' or 'Print time · 3 h 40 m'. */
                label: string;
                detail?: string;
                amount_paise: number;
            }[];
            /** @description Sum of lines with margin applied and rounded to a price ending in 9 rupees. */
            subtotal_paise: number;
            /** @description 0 when free. */
            shipping_paise: number;
            shipping_label?: string;
            total_paise: number;
            policy_version: string;
        };
        OrderItem: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            design_id: string;
            /** Format: uuid */
            version_id: string;
            version_no?: number;
            title: string;
            specs_line?: string;
            material_id: string;
            material_name?: string;
            qty: number;
            unit_price: components["schemas"]["price-breakdown.v1"];
            line_total_paise: number;
            /** @description Snapshot of the version assets at order time */
            assets?: {
                [key: string]: unknown;
            };
        };
        AddressInput: {
            /** @description Home or Office */
            label?: string;
            name: string;
            phone: string;
            line1: string;
            line2?: string;
            city: string;
            state: string;
            pincode: string;
            /** @default false */
            is_default: boolean;
        };
        Address: components["schemas"]["AddressInput"] & {
            /** Format: uuid */
            id: string;
        };
        Payment: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            order_id: string;
            /** @description mock or razorpay */
            gateway: string;
            /** @description Provider order or payment id */
            gateway_ref?: string | null;
            /** @enum {string} */
            status: "created" | "pending" | "succeeded" | "failed" | "refunded";
            method?: string | null;
            amount_paise: number;
            /** @constant */
            currency: "INR";
            /** @description Where the customer pays; the placeholder page for the mock gateway */
            pay_url?: string | null;
            invoice_number?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            finished_at?: string | null;
        };
        Shipment: {
            /** Format: uuid */
            id: string;
            carrier: string;
            awb?: string | null;
            /** @enum {string} */
            status: "created" | "picked_up" | "in_transit" | "out_for_delivery" | "delivered" | "returned";
            /** Format: date */
            eta?: string | null;
            tracking_url?: string | null;
            events?: {
                status?: string;
                message?: string;
                /** Format: date-time */
                at?: string;
            }[];
        };
        OrderEvent: {
            sequence: number;
            status: components["schemas"]["OrderStatus"];
            stage: components["schemas"]["OrderStage"];
            message: string;
            /** @description Studio, printer bay and layer height for the tracking board */
            detail?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            at: string;
        };
        Order: components["schemas"]["OrderSummary"] & {
            items: components["schemas"]["OrderItem"][];
            address: components["schemas"]["Address"];
            subtotal_paise: number;
            shipping_paise: number;
            shipping_label?: string;
            policy_version?: string;
            payment: components["schemas"]["Payment"];
            shipment?: components["schemas"]["Shipment"];
            events: components["schemas"]["OrderEvent"][];
            notify_whatsapp?: boolean;
            note?: string | null;
        };
        pbr: {
            /** @description sRGB hex */
            color: string;
            roughness: number;
            metalness: number;
            clearcoat?: number;
            clearcoat_roughness?: number;
            sheen?: number;
            sheen_color?: string;
        };
        CatalogItem: {
            slug: string;
            /** @description False until the item's template exists in the geometry service; the Shop shows a 'Coming soon' ribbon and POST /api/designs answers 422 template_not_available. */
            available: boolean;
            name: string;
            /** @enum {string} */
            category: "home_decor" | "nameplates" | "kitchen" | "desk_tech" | "gifting";
            description?: string;
            template_id: string;
            default_params: {
                [key: string]: unknown;
            };
            default_material: string;
            base_price_paise: number;
            /** @description e.g. 'Fits phones to 6.9″ · 92 × 78 × 120 mm · 64 g' */
            specs_line: string;
            environment?: string;
            media?: {
                kind?: string;
                url?: string;
            }[];
        };
    };
    responses: {
        /** @description Problem Details */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    type?: string;
                    title?: string;
                    status?: number;
                    detail?: string;
                    code?: string;
                };
            };
        };
    };
    parameters: {
        OrderId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
